// Problem: I need to create a way for the end user
// to specify a value, compare that value
// to one randomly generated by the computer, 
// and declare a winner based on that comparison;
// I then need to loop this process so that it 
// repeats 5 times and console.log the result
// of each round

function getComputerChoice () {
    let randomNumber = Math.random(); 
    if(randomNumber < .33) {return 'rock';
}   else if(randomNumber < .66) {return 'paper';
}   else {return 'scissors'}
}


let computerSelection = getComputerChoice(); 
let playerSelection = prompt('What will you choose?', 'Rock, Paper, or Scissors?').toLowerCase();


function playRound (computerSelection, playerSelection) {
    computerSelection = getComputerChoice();
    switch(playerSelection) {
        case 'rock':
            return computerSelection == 'paper' ? 'You Lose! Paper beats rock.' : 
             computerSelection == 'scissors' ? 'You Win! Rock beats scissors.' :
             "It's a tie! You both chose rock.";
        break;

        case 'paper':
            return computerSelection == 'scissors' ? 'You Lose! Scissors beats paper.' : 
             computerSelection == 'rock' ? 'You Win! Paper beats rock.' :
             "It's a tie! You both chose paper.";
        break; 

        case 'scissors':
            return computerSelection == 'rock' ? 'You Lose! Rock beats scissors.' :
             computerSelection == 'paper' ? 'You Win! Scissors beats paper.' :
             "It's a tie! You both chose scissors.";
        break;

        default: 
        return 'Invalid input! Please choose Rock, Paper, or Scissors';
    }
}

alert(playRound(computerSelection, playerSelection))

// function playRound (computerSelection, playerSelection) {
//    if(computerSelection == 'Rock' && playerSelection == 'Paper')
//        {return 'You win! Paper beats rock.'}